name: Pixeebot Fix Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: Pull request number
        required: false
        type: number
      file:
        description: File that will be sent
        default: pixeebot-fix-files/sonar
        required: true
        type: string

permissions:
  id-token: write

jobs:
  pixeebot-fix:
    name: Pixeebot Fix Workflow Dispatch
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Upload file and trigger analysis
        uses: pixee/upload-tool-results-action@76baca054328a3f414dd3300decc4a1cb5c87fd5
        with:
          tool: 'sonar'
          pr-number: ${{ github.event.inputs.pr-number }}
          file: ${{ github.event.inputs.file }}
