name: Pixeebot Fix

on:
  check_run:
    types: [ completed ]

permissions:
  id-token: write

jobs:
  pixeebot-fix:
    name: Pixeebot Fix
    if: ${{ !contains(github.actor, 'bot') && toJson(github.event.check_run.pull_requests) != '[]' && github.event.check_run.name == 'SonarCloud Code Analysis' }}
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Upload file and trigger analysis
        uses: JesusCotlamee/upload-tool-results-action@07a17fdddc0f32b784e5fe28bae122022dbc74c9
        with:
          tool: 'sonar'
      - name: Analysis sha
        shell: bash
        run: |
          ANALYSIS_SHA=${{ github.event.check_run.head_sha }}
          echo "$ANALYSIS_SHA"
