name: Pixeebot Fix

on:
  check_run:
    types: [ completed ]

permissions:
  id-token: write


jobs:
  pixeebot-fix:
    name: Pixeebot Fix
    if: ${{ !contains(github.actor, 'bot') && toJson(github.event.check_run.pull_requests) != '[]' && github.event.check_run.name == 'SonarCloud Code Analysis' }}
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Upload file and trigger analysis
        uses: JesusCotlamee/upload-tool-results-action@15a6d1c700b04867fb8258b30e14570af5fdd263
        with:
          tool: 'sonar'
