name: Pixeebot Fix Pull Request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  id-token: write

jobs:
  pixeebot-fix:
    name: Pixeebot Fix Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Upload file and trigger analysis
        uses: pixee/upload-tool-results-action@76baca054328a3f414dd3300decc4a1cb5c87fd5
        with:
          tool: 'sonar'
          file: pixeebot-fix-files/sonar
